/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddInfoForm: typeof import('./components/forms/AddInfoForm.vue')['default']
    AddPlaceForm: typeof import('./components/forms/AddPlaceForm.vue')['default']
    AddSizeForm: typeof import('./components/forms/AddSizeForm.vue')['default']
    AddTypeForm: typeof import('./components/forms/AddTypeForm.vue')['default']
    AddUserForm: typeof import('./components/forms/AddUserForm.vue')['default']
    AlertComponent: typeof import('./components/AlertComponent.vue')['default']
    CarTypeComponent: typeof import('./components/commons/CarTypeComponent.vue')['default']
    EditInfoDialog: typeof import('./components/EditInfoDialog.vue')['default']
    EditTypeDialog: typeof import('./components/EditTypeDialog.vue')['default']
    EditUserDialog: typeof import('./components/EditUserDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NotFoundCreateComponent: typeof import('./components/forms/NotFoundCreateComponent.vue')['default']
    OtherEmployeeDialog: typeof import('./components/OtherEmployeeDialog.vue')['default']
    PriceComponent: typeof import('./components/PriceComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeasonComponent: typeof import('./components/SeasonComponent.vue')['default']
  }
}
