/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/create/': RouteRecordInfo<'/create/', '/create', Record<never, never>, Record<never, never>>,
    '/datamatrix/': RouteRecordInfo<'/datamatrix/', '/datamatrix', Record<never, never>, Record<never, never>>,
    '/infos/': RouteRecordInfo<'/infos/', '/infos', Record<never, never>, Record<never, never>>,
    '/infos/[info_id]': RouteRecordInfo<'/infos/[info_id]', '/infos/:info_id', { info_id: ParamValue<true> }, { info_id: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/orders/': RouteRecordInfo<'/orders/', '/orders', Record<never, never>, Record<never, never>>,
    '/places/': RouteRecordInfo<'/places/', '/places', Record<never, never>, Record<never, never>>,
    '/sizes/': RouteRecordInfo<'/sizes/', '/sizes', Record<never, never>, Record<never, never>>,
    '/sizes/[size_id]': RouteRecordInfo<'/sizes/[size_id]', '/sizes/:size_id', { size_id: ParamValue<true> }, { size_id: ParamValue<false> }>,
    '/types/': RouteRecordInfo<'/types/', '/types', Record<never, never>, Record<never, never>>,
    '/types/[type_id]': RouteRecordInfo<'/types/[type_id]', '/types/:type_id', { type_id: ParamValue<true> }, { type_id: ParamValue<false> }>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
  }
}
